### ISSUE TITLE
RabbitMQ connection string limitations

### ISSUE THREAD

**Issue by mortenn** [Particular/TimeoutMigrationTool#318]
Using an amqps:// url for target connection string is accepted, but if the password contains a #, the tool crashes with the exception;
```
migrate-timeouts : Unhandled exception. System.UriFormatException: Invalid URI: Invalid port specified.
At line:6 char:1
+ migrate-timeouts preview sqlp --source $sqlserver --dialect mssqlserv ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...port specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Particular.TimeoutMigrationTool.RabbitMq.RabbitMqTimeoutTarget..ctor(ILogger logger, String targetConnectionString) in /_/src/TimeoutMigrationTool/RabbitMq/RabbitM
qTimeoutTarget.cs:line 16
   at Particular.TimeoutMigrationTool.Program.<>c__DisplayClass0_0.<<Main>b__23>d.MoveNext() in /_/src/TimeoutMigrationTool/Program.cs:line 373
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass8_0.<<OnExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Particular.TimeoutMigrationTool.Program.Main(String[] args) in /_/src/TimeoutMigrationTool/Program.cs:line 2035
```

While I would say this is an issue with the way System.Uri parses a string, I would have thought I could use the connection string format that you use elsewhere in the docs, ie.
```
host=rabbitmq.example.com;username=user;password=#;virtualhost=vhost;usetls=true
```
to work around this issue, but that also fails because System.Uri obviously cannot parse it.

**Comment by DavidBoike** [comment]
@mortenn I agree, this is a bug. The RabbitMQ transport uses a [ConnectionStringParser](https://github.com/Particular/NServiceBus.RabbitMQ/blob/master/src/targets/RabbitMqConnectionStringParser.cs) class rather than just stuffing the connection string into a URI.

We'll get this queued up for a fix in the near future.

In the meantime, the workaround I would suggest is to create a temporary user in the RabbitMQ cluster with a long and secure password that doesn't happen to contain any non-URI-parseable characters. After migration is complete, remove the temporary user.

**Comment by DavidBoike** [comment]
I guess it's a little more than that, as just replacing the `#` in your connection string with `abc` isn't URI-parseable either.

In our [integration tests](https://github.com/Particular/TimeoutMigrationTool/blob/master/src/TimeoutMigrationTool.RabbitMq.IntegrationTests/RabbitMqTimeoutsTargetTests.cs#L25) our connection string is `amqp://guest:guest@localhost:5672/` - as you note, AMQP URLs work, but `amqp://guest:gu#est@localhost:5672/` does not. I wonder if using `%23` (the encoded representation of `#`) would work. If it does not, my original recommendation stands to create a temporary user with URI-parseable password, and then fit it into the amqp URL pattern.

**Comment by mortenn** [comment]
I am not planning on using this tool for the upcoming migration anyway, as I am only getting "no endpoints" when I try running the preview, still figured I'd report this issue though, as it may help someone else out in the future

**Comment by DavidBoike** [comment]
We're closing this issue because we have made an internal decision to prefer the standard AMQP URI connection format, rather than the non-standard connection string format.

Trying to use a character like `#` in the connection string, since it's a Uri and `#` is a reserved character, requires Uri-encoding it.

If there is something else that you can only do with the parsed format, and not with an AMQP URI, please let us know.
